import { Component, OnInit, inject, NgZone } from '@angular/core';
import { DatePipe } from '@angular/common';

import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { AutosizeModule } from 'ngx-autosize';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatMenuModule } from '@angular/material/menu';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressSpinner } from '@angular/material/progress-spinner';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-training',
  standalone: true,
  templateUrl: './training.component.html',
  styleUrls: ['./training.component.scss'],
  imports: [
    DatePipe,
    FormsModule,
    AutosizeModule,
    MatButtonModule,
    MatExpansionModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonToggleModule,
    MatSidenavModule,
    MatMenuModule,
    MatCardModule,
    MatChipsModule,
    MatProgressSpinner
  ]
})
export class TrainingComponent implements OnInit {

    constructor(
    private zone: NgZone,
    private http: HttpClient,
    private route: ActivatedRoute
  ) {  }
  private ngZone = inject(NgZone);

  duration = {
    value: 0,
    unit: 'min' as 'min' | 'sec'
  };
  
  parametersVisible: boolean = false;

  obligatoire!: string;
  type_saisie: string = 'saisie_manuelle';
  msg_obligatoire: string = '';
  consigne: string = '';

  typeComponent: string = 'OuverteComponent';
  componentId: any;
  questions: any = [];
  isCollapse: boolean = false;
  branchements: any[] = [];
  libelleQuestion: string = '';
  reponseQuestion: string = '';
  activeTheme: string = '';
  selectedTheme: string = '';
  selectedSubTheme: string = '';
  isAutoGenerated: boolean = false;
  initialContent: string[] = [];
  isLoading = false;

  id_audio: string = '';
  mediaRecorder!: MediaRecorder;
  audioChunks: Blob[] = [];
  audioUrl?: string;
  isRecording = false;
  audioBlob?: Blob;
  audioElement?: HTMLAudioElement;

  // Historique des échanges question / réponse
  history: { question: string; answer: string; createdAt: Date }[] = [];



  ngOnInit() {
    this.route.queryParamMap.subscribe((params) => {
      this.selectedTheme = params.get('themeLabel') || params.get('theme') || '';
      this.selectedSubTheme = params.get('subThemeLabel') || params.get('subTheme') || '';
    });
  }

  ngAfterViewInit() {}

  startRecording() {
    this.isRecording = true;
    this.audioChunks = [];

    navigator.mediaDevices.getUserMedia({ audio: true }).then((stream) => {
        // 🎙️ MediaRecorder
        this.mediaRecorder = new MediaRecorder(stream);

        this.mediaRecorder.ondataavailable = (event) => {
          this.audioChunks.push(event.data);
        };

        this.mediaRecorder.onstop = () => {
          // Crée le blob audio
          this.audioBlob = new Blob(this.audioChunks, { type: 'audio/webm' });
          this.audioUrl = URL.createObjectURL(this.audioBlob);
          this.audioElement = new Audio(this.audioUrl);
          // Stoppe le micro pour libérer la ressource
          stream.getTracks().forEach((track) => track.stop());

          // Envoie au backend pour transcription
          this.sendAudioToBackend();
        };

        this.mediaRecorder.start();
      })
      .catch((err) => {
        console.error('Erreur accès micro :', err);
        this.isRecording = false;
      });
  }
  stopRecording() {
    if (!this.isRecording) return;
    this.isRecording = false;
    this.mediaRecorder?.stop();
  }

  async playAudio() {
    if (!this.id_audio) return;

    this.zone.run(() => {
      this.isLoading = true;
    });

    try {
      this.http.get(`http://localhost:8002/themes/get_audio_file/${this.id_audio}`, { responseType: 'blob' }).subscribe((blob: Blob | MediaSource) => {
        this.audioUrl = URL.createObjectURL(blob);
        this.audioElement = new Audio(this.audioUrl);
        this.audioElement.currentTime = 0;
        this.audioElement.play();
      });
    } catch (err) {
      console.error('Erreur getting audio file :', err);
    } finally {
      this.zone.run(() => {
        this.isLoading = false;
      });
    }
  }

  async sendAudioToBackend() {
    if (!this.audioBlob) return;

    this.zone.run(() => {
      this.isLoading = true;
    });

    const formData = new FormData();
    formData.append('audio', this.audioBlob, 'reponse.webm');

    try {
      const response = await fetch('http://localhost:8002/themes/get_transcribe_audio', {
        method: 'POST',
        body: formData
      });

      const data = await response.json();
      this.zone.run(() => {
        this.libelleQuestion = data.text || '';
        this.reponseQuestion = '';
        this.id_audio = data.id || '';

        // Ajout automatique dans l'historique dès que la question est transcrite
        this.history.unshift({
          question: (this.libelleQuestion || '').trim(),
          answer: (this.reponseQuestion || '').trim(),
          createdAt: new Date()
        });
      });
    } catch (err) {
      console.error('Erreur transcription backend :', err);
    } finally {
      this.zone.run(() => {
        this.isLoading = false;
      });
    }
  }

  parametersIsVisible() {
    this.parametersVisible = !this.parametersVisible;
  }

  setValueToExpanded() {
    // this.expanded=!this.expanded;
  }
  collapse_question(): void {
    this.isCollapse = !this.isCollapse;
    // this.expanded = false;
  }

  receiveQuestion(data: string) {
    this.libelleQuestion = data;
  }
  receiveBranchements(branchementAdded: any) {
    this.branchements = branchementAdded;
  }
  markAsChanged() {
    this.isAutoGenerated = false;
  }

  /**
   * Ajoute la paire question / réponse courante à l'historique.
   * Un format "chat" sera ensuite affiché dans la zone d'historique.
   */
  addToHistory() {
    const question = this.libelleQuestion?.trim();
    const answer = this.reponseQuestion?.trim();

    if (!question && !answer) {
      return;
    }

    this.history.unshift({
      question: question || '',
      answer: answer || '',
      createdAt: new Date()
    });

    // On vide les zones de saisie pour le prochain échange
    this.libelleQuestion = '';
    this.reponseQuestion = '';
  }

  deleteHistoryItem(index: number) {
    if (index < 0 || index >= this.history.length) {
      return;
    }

    const shouldDelete = window.confirm('Voulez-vous supprimer cet échange de l’historique ?');
    if (!shouldDelete) {
      return;
    }

    this.history.splice(index, 1);
  }
}
